# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false
    handle_all_throwables: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    #esi: true
    #fragments: true
    php_errors:
        log: true

    http_client:
        scoped_clients:
            f1:
                base_uri: http://ergast.com/api/f1
            actu:
                base_uri: http://127.0.0.1:8001/api
            weather:
                base_uri: https://api.open-meteo.com

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
